### ISSUE TITLE
Add open graph meta tags to all pages

### ISSUE THREAD

**Issue by bryanchug** [cruxph/cruxph.github.io#7]
See facebook open graph meta tags

**Comment by jcdelfinado** [comment]
Added tags. Tried posting on facebook; the image does not display. 
![selection_008](https://cloud.githubusercontent.com/assets/6530419/5913746/0b9f595a-a624-11e4-90ef-e01e198ddd4e.png)

**Comment by jcdelfinado** [comment]
Images display only for some of the pages. 
![selection_009](https://cloud.githubusercontent.com/assets/6530419/5914299/00a2aade-a62e-11e4-9509-a68cf1fc0058.png)

[Facebook object debugger](https://developers.facebook.com/tools/debug/) has this warning: 
![selection_010](https://cloud.githubusercontent.com/assets/6530419/5914934/3466e9a6-a639-11e4-908e-75b5cc35d65c.png)

**Comment by jcdelfinado** [comment]
Looks like a problem with Github Pages content delivery.
